### ISSUE TITLE
More of a feature request...

### ISSUE THREAD

**Issue by redlegoman** [AndersUk/DNSMasqBlockIffyDomains#1]
Could you modify the build program to exclude domains ending with the string in the whitelist?
i.e.
"`bbc.co.uk`" in the whitelist would mean that "`server1.bbc.co.uk`" and "`host2.bbc.co.uk`" as well as "`bbc.co.uk`" were removed from the blocklist?

**Comment by AndersUk** [comment]
Feature update done.
